### PR TITLE
feat(spell): Implement Arms of Hadar

### PR DESCRIPTION
**Pull request by nickelpro**
[The Arms. The Arms of Hadar. The Arms chosen specially for Hadar. Hadar's Arms.](https://youtu.be/NcKGw-IO5Uc)

System data is obvious, sets up duration, range, units, and flags in a way that midi understands to do its business.

The effects prop is my preferred way to handle abilities that apply status effects, just throw that bad boy right into the effects array, whole thing. We might want a way to shorthand this that the DataConverter understands and can unpack instead of this approach, perhaps even invoking Dfred's API to get the correct effect data instead of hard coding it into abilities ourselves.

But for now, this works.

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
Duplicating CE effects here is pretty meh; I'll wire up something better. Maybe:

```json
"effects": [
  {"convenientEffect": "Reaction"}
]
````

but I'll have to go fiddle with the API and see what's what

**Comment by nickelpro** [comment]
I'll update this next time I'm sitting at a dev machine

**Comment by nickelpro** [comment]
Tested working with CE shorthand, ready for merge

**Comment by TheGiddyLimit** [comment]
@nickelpro conflicts with your antimagic field PR, by the looks 🎉

**Review by TheGiddyLimit — APPROVED** [review]
truly based

**Pull request merged**
