### PR TITLE
Disallow unknown properties in entity schemas

### LINKED ISSUE #47: Switch to (at least) JSON schema spec Draft 2019-09 and utilize `unevaluatedProperties`
This will allow us to write tighter schemas, without sacrificing readability.

See:

- https://json-schema.org/understanding-json-schema/reference/object.html#extending-closed-schemas
- https://ajv.js.org/json-schema.html#draft-2019-09  /  https://ajv.js.org/guide/schema-language.html#draft-2019-09-and-draft-2020-12

### PR DESCRIPTION
**Pull request by TheGiddyLimit**
This makes it easier to develop new entities, and improves our automated testing to catch obvious errors.

Closes #47

### CODE REVIEW

**Comment by TheGiddyLimit** [comment]
@revilowaldow fyi/thoughts?

**Comment by revilowaldow** [comment]
> @revilowaldow fyi/thoughts?

- ~~Where did the `convenientEffectObject` go?~~
- `definitions` was [deprecated in 2019-09](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.5) in favour of `$defs`
- I think `$id` changed a bit in 2019-09, I don't know much about URI fragments, maybe [worth a check](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.2)? 
- Can't see any `"items": []` rather than `"items":{}` so think we're safe for that breaking change.
- I saw you added multi-threading to the validation dependency, it actually got materially slower for me running against the whole homebrew repo. Is that a `your free cloud server is shit` or something in the code? I'd have expected it to get faster.

**Comment by TheGiddyLimit** [comment]
> * ~Where did the `convenientEffectObject` go?~

I clicked "pull and rebase" and my IDE did neither of these things!

> * `definitions` was [deprecated in 2019-09](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.5) in favour of `$defs`

Noted; fixed ~and having now at least skimmed the migration pages instead of just the headlines, everything else looks "good enough"~

> * I think `$id` changed a bit in 2019-09, I don't know much about URI fragments, maybe [worth a check](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.2)?

From what I can see, setting an `$anchor` is a way of force-setting `https://example.com/my-schema.json#AnchorName` as a reference to the `$anchor`'d part of the schema, which doesn't seem useful right now

> * Can't see any `"items": []` rather than `"items":{}` so think we're safe for that breaking change.

Yeah we never used tuples anywhere, so that turned out to be a non-issue

> * I saw you added multi-threading to the validation dependency, it actually got materially slower for me running against the whole homebrew repo. Is that a `your free cloud server is shit` or something in the code? I'd have expected it to get faster.

The multi-threading was me reacting to the thing getting way fucking slower; from the AJV docs:

> #### Draft-2019-09 features performance cost (even when not used)
> Supporting dynamic recursive references and unevaluatedProperties/unevaluatedItems keywords adds additional generated code even to the validation functions where these features are not used (when possible, Ajv determines which properties/items are "unevaluated" at compilation time, but support for dynamic references always adds additional generated code). If you are not using these features in your schemas it is recommended to use default Ajv export with JSON-Schema draft-07 support.

I don't really want to be stuck using ye-olde draft 7, and I _especially_ don't want to be stuck using it in only half the places using the JSON testing code and/or having half-migrated projects. This "works" today, and I'd rather try to improve it (make better homebrew tooling which only checks modified files, or commits authored on your current branch, or...) from here than never be able to update any JSON testing lib again

**Comment by revilowaldow** [comment]
Excellent sounds good.

The thing with `$id` when we went around it previously for homebrew stuff was we needed the `../` shenanigans to make it work in VSCode unless it was given a fixed `https://` location in the `$id`.
Wanted to make sure it wouldn't break something along those lines.

Ahhh I see, it's the classic waterfall chart where I only saw the start and end and not the middle.
Yeah that's very fair, going to the most recent spec is always sensible. 
I might give the site schema a once-over just in case there's anything there but I imagine it should be fine.
image
(numbers pulled out of my 🍑)

(I think the pf2e stuff has [some tuples](https://github.com/Pf2eToolsOrg/Pf2eTools/blob/289869a1e951e8eb598a3c525775468ff77db221/test/schema-template/utils.json#L1657) )

**Comment by TheGiddyLimit** [comment]
Digging in a bit, the brew repo ain't looking so healthy 🤔 Validating the site's data runs just fine (for me, at least), using the still-single-threaded 2020-12 validator; it feels a _touch_ slower than it once was, but nothing unexpected.

Several brews are taking >seconds to validate, however, with the tail reaching as high as 30 seconds(!). Here's a list of the >5 sec offenders (leading number is arbitrary and denotes a run on my end):

```
3 - collection/Loot Tavern; Heliana's Guide To Monster Hunting.json                                  5029
1 - creature/Anthony Turco; Korranberg Chronicle's Threat Dispatch.json                              5092
2 - collection/Yorviing; Yorviing's Arcane Grimoire.json                                             5187
1 - collection/Yorviing; Yorviing's Arcane Grimoire.json                                             5243
3 - collection/Yorviing; Yorviing's Arcane Grimoire.json                                             5285
1 - class/Middle Finger of Vecna; Binder.json                                                        5346
1 - adventure/Adventurers League; DDEX1-04 - Dues for the Dead.json                                  5597
2 - adventure/D&D Beyond; Don't Say Vecna.json                                                       5720
3 - action/Sample - Giddy; Extinguish.json                                                           5725
3 - adventure/Adventurers League; DDIA-MORD Rrakkma.json                                             5791
1 - collection/Arcana Games; Arkadia.json                                                            5817
3 - class/Middle Finger of Vecna; Binder.json                                                        5817
2 - adventure/Kelsey Dionne; The Secrets of Skyhorn Lighthouse.json                                  5875
1 - action/Sample - Giddy; Extinguish.json                                                           5889
2 - adventure/Adventures Await; Shipwreck of the Sea Mephit.json                                     5922
3 - adventure/arcanist; The Delian Tomb.json                                                         5967
2 - collection/Flore; Explorer's guide to Xhoria.json                                                5982
3 - adventure/D&D Duet; Third Times the Charm.json                                                   6014
3 - adventure/DMDave; Assault on Quabus.json                                                         6020
3 - adventure/Adventures Await; Shipwreck of the Sea Mephit.json                                     6050
3 - adventure/Adventurers League; DDEX1-04 - Dues for the Dead.json                                  6059
3 - adventure/Adventures Await; Wrath of the Demon Lord.json                                         6075
3 - adventure/Kobold Press; Book of Lairs.json                                                       6077
3 - adventure/Kobold Press; Tome of Beasts 2 Lairs.json                                              6085
3 - adventure/Adventures Await; The Curse of Dusk Hollow.json                                        6212
1 - adventure/Adventurers League; DDEX1-03 - Shadows Over the Moonsea.json                           6233
2 - adventure/Adventurers League; DDEX1-02 - Secrets of Sokol Keep.json                              6324
3 - adventure/D&D Duet; Second Glance.json                                                           6327
3 - adventure/D&D Beyond; Don't Say Vecna.json                                                       6333
2 - collection/Arcana Games; Arkadia.json                                                            6335
3 - collection/Flore; Explorer's guide to Xhoria.json                                                6335
2 - adventure/Adventurers League; DDEX1-01 - Defiance in Phlan.json                                  6364
2 - adventure/Adventurers League; DDIA-MORD Rrakkma.json                                             6415
2 - class/Middle Finger of Vecna; Binder.json                                                        6457
1 - adventure/Adventurers League; DDEX1-02 - Secrets of Sokol Keep.json                              6463
1 - adventure/Adventures Await; Shipwreck of the Sea Mephit.json                                     6479
1 - adventure/Adventurers League; DDIA-MORD Rrakkma.json                                             6525
1 - adventure/Adventures Await; The Curse of Dusk Hollow.json                                        6585
3 - adventure/Anthony Joyce; The Blood Hunter Adventure.json                                         6631
3 - collection/Arcana Games; Arkadia.json                                                            6673
3 - adventure/Kelsey Dionne; The Secrets of Skyhorn Lighthouse.json                                  6816
1 - adventure/Adventurers League; DDEX1-01 - Defiance in Phlan.json                                  6992
2 - adventure/Adventurers League; DDEX1-03 - Shadows Over the Moonsea.json                           7069
1 - collection/Flore; Explorer's guide to Xhoria.json                                                7386
2 - adventure/DMDave; Assault on Quabus.json                                                         7689
2 - adventure/Adventures Await; The Dueling Knight's Fungeon Dungeon.json                            7771
2 - adventure/Kelsey Dionne; Temple of the Basilisk Cult.json                                        7772
2 - adventure/Adventures Await; The Fangs of Zengar.json                                             7858
2 - adventure/Adventurers League; DDEX1-04 - Dues for the Dead.json                                  7898
2 - adventure/D&D Duet; Third Times the Charm.json                                                   8190
1 - adventure/D&D Duet; Third Times the Charm.json                                                   8197
2 - adventure/Adventures Await; Wrath of the Demon Lord.json                                         8225
2 - adventure/Kobold Press; Book of Lairs.json                                                       8261
2 - action/Sample - Giddy; Extinguish.json                                                           8266
2 - adventure/Adventures Await; The Curse of Dusk Hollow.json                                        8266
1 - adventure/D&D Duet; First Blush.json                                                             8268
2 - adventure/D&D Duet; First Blush.json                                                             8275
2 - adventure/Kobold Press; Tome of Beasts 2 Lairs.json                                              8346
1 - adventure/Adventures Await; Wrath of the Demon Lord.json                                         8371
2 - adventure/D&D Duet; Second Glance.json                                                           8403
1 - adventure/Kelsey Dionne; The Secrets of Skyhorn Lighthouse.json                                  8422
2 - adventure/arcanist; The Delian Tomb.json                                                         8461
1 - adventure/arcanist; The Delian Tomb.json                                                         8488
1 - adventure/D&D Beyond; Don't Say Vecna.json                                                       8664
1 - adventure/Kobold Press; Tome of Beasts 2 Lairs.json                                              8745
1 - adventure/D&D Duet; Second Glance.json                                                           8833
1 - adventure/Kobold Press; Book of Lairs.json                                                       8898
1 - adventure/Adventures Await; The Dueling Knight's Fungeon Dungeon.json                            8903
2 - class/Giffyglyph; Class Compendium.json                                                          9050
3 - adventure/Kelsey Dionne; Temple of the Basilisk Cult.json                                        9052
1 - adventure/Kelsey Dionne; Temple of the Basilisk Cult.json                                        9077
2 - adventure/JVC Parry; Call from the Deep.json                                                     9140
1 - adventure/DMDave; Assault on Quabus.json                                                         9339
1 - adventure/Adventures Await; The Fangs of Zengar.json                                             9358
3 - adventure/D&D Duet; First Blush.json                                                             9380
2 - adventure/Anthony Joyce; The Blood Hunter Adventure.json                                         9452
3 - adventure/Adventurers League; DDEX1-03 - Shadows Over the Moonsea.json                           9604
3 - adventure/Adventurers League; DDEX1-01 - Defiance in Phlan.json                                  9822
1 - class/Giffyglyph; Class Compendium.json                                                          9823
3 - adventure/Adventures Await; The Dueling Knight's Fungeon Dungeon.json                            9926
1 - adventure/Anthony Joyce; The Blood Hunter Adventure.json                                         9972
1 - collection/Haven; All the Lights in the Sky are Stars.json                                       9976
2 - collection/Haven; All the Lights in the Sky are Stars.json                                       10125
1 - adventure/JVC Parry; Call from the Deep.json                                                     10270
3 - adventure/Adventures Await; The Fangs of Zengar.json                                             10277
3 - adventure/Adventurers League; DDEX1-02 - Secrets of Sokol Keep.json                              10608
3 - class/Giffyglyph; Class Compendium.json                                                          10890
3 - collection/Haven; All the Lights in the Sky are Stars.json                                       11167
1 - collection/Mage Hand Press; Dark Matter.json                                                     12240
2 - collection/Mage Hand Press; Dark Matter.json                                                     12419
3 - adventure/JVC Parry; Call from the Deep.json                                                     13289
1 - collection/QL Games; Tasha's Crucible of Everything Else - Volume 1.json                         15939
2 - collection/QL Games; Tasha's Crucible of Everything Else - Volume 1.json                         16835
3 - collection/Mage Hand Press; Dark Matter.json                                                     17412
3 - collection/QL Games; Tasha's Crucible of Everything Else - Volume 1.json                         21058
1 - creature/Onyx Path; Scarred Lands Creature Collection.json                                       31020
2 - creature/Onyx Path; Scarred Lands Creature Collection.json                                       31620
1 - collection/Matthew Mercer; TalDorei Campaign Guide.json                                          33730
2 - collection/Matthew Mercer; TalDorei Campaign Guide.json                                          33836
3 - creature/Onyx Path; Scarred Lands Creature Collection.json                                       35645
3 - collection/Matthew Mercer; TalDorei Campaign Guide.json                                          36500
```

**Comment by TheGiddyLimit** [comment]
With `bookData` being the precise culprit 👀 
```
[        JSON]  Validating "./scratch/sample-file.json"...
Without book completed in 33.778s
[        JSON]  Validating "./scratch/sample-file.json"...
Without bookData completed in 2.315s
[        JSON]  Validating "./scratch/sample-file.json"...
Without race completed in 30.309s
[        JSON]  Validating "./scratch/sample-file.json"...
Without deity completed in 30.005s
[        JSON]  Validating "./scratch/sample-file.json"...
Without subclass completed in 30.236s
[        JSON]  Validating "./scratch/sample-file.json"...
Without item completed in 31.325s
[        JSON]  Validating "./scratch/sample-file.json"...
Without background completed in 29.982s
[        JSON]  Validating "./scratch/sample-file.json"...
Without feat completed in 30.063s
[        JSON]  Validating "./scratch/sample-file.json"...
Without monster completed in 30.222s
[        JSON]  Validating "./scratch/sample-file.json"...
Without variantrule completed in 30.250s
[        JSON]  Validating "./scratch/sample-file.json"...
Without subclassFeature completed in 31.045s
```

**Comment by revilowaldow** [comment]
> With `bookData` being the precise culprit 👀

See also `_schema-fast`...

Would moving `entry.json` to the newer system for recursive schemas offer performance improvements?
https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.4.2

**Comment by TheGiddyLimit** [comment]
Worth a shot, certainly

In the meantime:

```
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 0 completed in avg. 31.770s
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 1 completed in avg. 30.622s
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 2 completed in avg. 3.066s
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 3 completed in avg. 30.484s
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 4 completed in avg. 31.189s
[        JSON]  Validating "./scratch/sample-file.json"...
Without chapter 5 completed in avg. 30.391s
```

one of these is not like the others

**Comment by TheGiddyLimit** [comment]
Meh, it's just because that one chapter is the bulk of the text. False alarm 😔

**Comment by revilowaldow** [comment]
For what it's worth, one of the only nasty changes made in site>homebrew.
https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/blob/63f83fe9fe107404ed31f5600273e37a56056411/test/schema-template/entry.json#L72

Changing this is likely to fail every file in the repo but correcting it may improve performance. I didn't want to go near it originally.

**Comment by TheGiddyLimit** [comment]
`$dynamicRef`/`$dynamicAnchor` (the 2020-12 version of the `recursive` stuff) didn't do anything, let's try requiring types...

**Comment by TheGiddyLimit** [comment]
And there it is:

```
[        JSON]  Validating "./scratch/sample-file.json"...
Completed in 3.213s
```

**Comment by revilowaldow** [comment]
Shotgun not fixing the homebrew if you haven't already <3

**Comment by TheGiddyLimit** [comment]
ach I'll just make a branch and delete all the non-compliant brew
sorted!

**Comment by revilowaldow** [comment]
I lack the skills to do it programatically unfortunately 
Will definitely fix my own files if it needs doing one by one though

**Comment by TheGiddyLimit** [comment]
Changes now made on the brew side; here's every >5sec JSON. Some dodgy outliers in there (`Sample - Giddy; Extinguish.json`??) but (a) sample size of 1, and (b), Good Enough:tm:.

```
adventure/Adventurers League; DDEX1-02 - Secrets of Sokol Keep.json                                  5161
adventure/Adventures Await; Wrath of the Demon Lord.json                                             5199
action/Sample - Giddy; Extinguish.json                                                               5204
adventure/Adventurers League; DDEX1-01 - Defiance in Phlan.json                                      5269
adventure/Adventurers League; DDEX1-03 - Shadows Over the Moonsea.json                               5305
adventure/Adventures Await; The Fangs of Zengar.json                                                 5324
adventure/Adventurers League; DDEX1-04 - Dues for the Dead.json                                      5348
adventure/Adventures Await; The Dueling Knight's Fungeon Dungeon.json                                5349
adventure/D&D Duet; First Blush.json                                                                 5349
adventure/Adventurers League; DDIA-MORD Rrakkma.json                                                 5392
adventure/Kelsey Dionne; The Secrets of Skyhorn Lighthouse.json                                      5397
adventure/D&D Duet; Second Glance.json                                                               5412
adventure/D&D Beyond; Don't Say Vecna.json                                                           5440
adventure/D&D Duet; Third Times the Charm.json                                                       5482
adventure/Adventures Await; The Curse of Dusk Hollow.json                                            5493
adventure/DMDave; Assault on Quabus.json                                                             5520
adventure/Adventures Await; Shipwreck of the Sea Mephit.json                                         5549
adventure/Kobold Press; Tome of Beasts 2 Lairs.json                                                  5613
adventure/arcanist; The Delian Tomb.json                                                             5627
adventure/Kelsey Dionne; Temple of the Basilisk Cult.json                                            5757
adventure/Anthony Joyce; The Blood Hunter Adventure.json                                             5777
adventure/Kobold Press; Book of Lairs.json                                                           5815
adventure/JVC Parry; Call from the Deep.json                                                         6262
```

**Comment by revilowaldow** [comment]
Much faster! 👏

**Pull request merged**
